<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>yottacast-core</AssemblyName>
    <RootNamespace>Yottacast.Ipc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Proto/**/*.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.67.0" PrivateAssets="All" />
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yottacast.Core\Yottacast.Core.csproj" />
  </ItemGroup>
</Project>
