namespace Yottacast.Core.Search.SystemSettings;

internal static class BuiltinPanels {
    public static readonly IReadOnlyList<SystemSettingsPanel> All = [
        new("Wi-Fi",               "com.apple.preference.network"),
        new("Bluetooth",           "com.apple.preferences.Bluetooth"),
        new("Network",             "com.apple.preference.network"),
        new("VPN",                 "com.apple.preference.network"),
        new("Notifications",       "com.apple.preference.notifications"),
        new("Focus",               "com.apple.preference.notifications"),
        new("Sound",               "com.apple.preference.sound"),
        new("Screen Time",         "com.apple.preference.screentime"),
        new("General",             "com.apple.preference.general"),
        new("Appearance",          "com.apple.preference.general"),
        new("Accessibility",       "com.apple.preference.universalaccess"),
        new("Control Center",      "com.apple.preference.controllcenter"),
        new("Siri & Spotlight",    "com.apple.preference.speech"),
        new("Privacy & Security",  "com.apple.preference.security"),
        new("Privacy",             "com.apple.preference.security"),
        new("Security",            "com.apple.preference.security"),
        new("Desktop & Dock",      "com.apple.preference.exposeclassic"),
        new("Stage Manager",       "com.apple.preference.exposeclassic"),
        new("Mission Control",     "com.apple.preference.exposeclassic"),
        new("Displays",            "com.apple.preference.displays"),
        new("Wallpaper",           "com.apple.preference.desktopscreeneffect"),
        new("Screen Saver",        "com.apple.preference.desktopscreeneffect"),
        new("Battery",             "com.apple.preference.battery"),
        new("Energy Saver",        "com.apple.preference.battery"),
        new("Lock Screen",         "com.apple.preference.security"),
        new("Touch ID & Password", "com.apple.systempreferences.LocalAuthenticationPrefPane"),
        new("Users & Groups",      "com.apple.preferences.users"),
        new("Passwords",           "com.apple.Passwords"),
        new("Apple ID",            "com.apple.systempreferences.AppleIDPrefPane"),
        new("Family Sharing",      "com.apple.systempreferences.FamilySharingPrefPane"),
        new("Internet Accounts",   "com.apple.preference.internetaccounts"),
        new("Game Center",         "com.apple.systempreferences.GameCenterPrefPane"),
        new("Wallet & Apple Pay",  "com.apple.systempreferences.WalletPrefPane"),
        new("Keyboard",            "com.apple.preference.keyboard"),
        new("Trackpad",            "com.apple.preference.trackpad"),
        new("Mouse",               "com.apple.preference.mouse"),
        new("Printers & Scanners", "com.apple.preference.printfax"),
        new("Date & Time",         "com.apple.preference.datetime"),
        new("Language & Region",   "com.apple.Localization"),
        new("Storage",             "com.apple.preference.storage"),
        new("Sharing",             "com.apple.preferences.sharing"),
        new("Time Machine",        "com.apple.prefs.backup"),
        new("Software Update",     "com.apple.preferences.softwareupdate"),
        new("Startup Disk",        "com.apple.preference.startupdisk"),
        new("Extensions",          "com.apple.preference.extensions"),
    ];
}
